# Server configuration
server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s
  shutdown_timeout: 10s
  # Gin mode: debug, release, test
  mode: "release"

# Processing configuration
processing:
  worker_count: 10      # Must match your struct field name (worker_count, not worker_pool_size)
  buffer_size: 10000    # Size of the buffered channel for incoming data
  batch_size: 100       # Number of records to process in a batch
  flush_interval: 5s

# Storage configuration
storage:
  # PostgreSQL / TimescaleDB 
  postgres:
    host: "localhost"
    port: 5432
    database: "analytics"
    user: "youruser"
    password: "yourpassword"
    max_connections: 25

  # Redis configuration
  redis:
    address: "localhost:6379"
    password: ""
    db: 0
    pool_size: 50       # Fixed: max_size → pool_size to match your struct

# Time window configuration
window:                 # Fixed: windows → window (singular to match your struct)
  tumbling:
    - size: 1m
      metrics: ["count", "sum", "avg"]
    - size: 5m
      metrics: ["count", "p95", "p99"]

  # Sliding windows (overlapping intervals)
  sliding:
    - size: 5m
      step: 1m
      metrics: ["rate", "unique"]

# Logging configuration
logging:
  level: "info"         # debug, info, warn, error
  format: "json"        # json, console
  output: "stdout"      # stdout, stderr, file

# Metrics and monitoring
monitoring:
  prometheus:
    enabled: true
    port: 9090
    path: "/metrics"